import Head from 'next/head';
import About from './about';
import Portfolio from './portfolio';
import Link from 'next/link';

export default function Home() {
	return (
		<div className='homepage'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='homepage__wrapper'>
				<div className='homepage__banner'>
					<div className='homepage__title'>
						<h1>
							<span>Alex</span>andru Folea
						</h1>
						<p>Front-end Developer</p>
					</div>
				</div>
				<div className='homepage__categories'>
					<div className='about'>
						<Link href='/about'>About</Link>
					</div>
					<div className='portfolio'>
						<Link href='/portfolio'>Portfolio</Link>
					</div>
				</div>
			</div>
		</div>
	);
}
