import Head from 'next/head';
import About from '../components/About';
import Link from 'next/link';
import Navbar from '../components/Navbar';

export default function Home({ projects }) {
	// console.log(projects);
	const portfolio = '<portfolio/>';

	return (
		<div className='homepage' id='home'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<div className='homepage__wrapper'>
				<div className='homepage__banner'>
					<div className='homepage__title'>
						<h1>CREATIVE</h1>
						<h3>DEVELOPER</h3>
						<span>SENSIBLE TO FRONT-END</span>
					</div>
				</div>
				<div className='homepage__categories'>
					<div className='about'>
						<Link href='#about'>about</Link>
					</div>
					<div className='portfolio'>
						<Link href='/portfolio'>{portfolio}</Link>
					</div>
				</div>
			</div>
			<About />
		</div>
	);
}
